### ISSUE TITLE
Update bower.json

### ISSUE THREAD

**Issue by ToniChaz** [jackrabbitsgroup/angular-datetimepicker#1]
Hi, you need this line in your **bower.json** file

**"main": ["./pikaday/*", "./datetimepicker.min.js", "./datetimepicker.min.css"],**

below of version line: 4
because grunt he dont push the libraries in the index.html

**Comment by lukemadera** [comment]
You're welcome to add that for your project if you like but the install readme clearly states how to manually do this:
https://github.com/jackrabbitsgroup/angular-datetimepicker/blob/master/README.md

**Comment by ToniChaz** [comment]
Ok thank you. It was just a recommendation.
